content_generation:
  posts:
    enabled: true
    count: 2
    genres: 
      - abstract
      - game
      - movie
      - portrait
      - photography
      - fantasy
    
    # Style configurations for each genre
    styles:
      abstract:
        - "surreal"
        - "modern"
        - "cubist"
        - "minimalist"
      game:
        - "pixel art"
        - "hand-painted"
        - "3D render"
      movie:
        - "cinematic"
        - "dramatic"
        - "realistic"
      portrait:
        - "realistic"
        - "digital painting"
        - "classical"
      photography:
        - "cinematic"
        - "photorealistic"
        - "documentary"
      fantasy:
        - "dark surrealism"
        - "fantasy painting"
        - "mythical"
    
    # Theme configurations
    themes:
      abstract:
        - "geometric chaos"
        - "color burst"
        - "dreamscapes"
      game:
        - "cyberpunk city"
        - "alien planet"
        - "fantasy world"
      movie:
        - "sci-fi epic"
        - "cosmic horror"
        - "historical drama"
      portrait:
        - "fantasy character"
        - "mystical figure"
        - "regal elegance"
      photography:
        - "urban exploration"
        - "minimalist design"
        - "nature's beauty"
      fantasy:
        - "mystical realms"
        - "ancient gods"
        - "post-apocalyptic worlds"
    
    # Color palette configurations
    palettes:
      abstract:
        - "vivid"
        - "monochrome"
        - "gradient"
      game:
        - "vivid"
        - "dark"
        - "neon"
      movie:
        - "monochrome"
        - "cool tones"
        - "warm tones"
      portrait:
        - "soft pastels"
        - "monochrome"
        - "vivid"
      photography:
        - "natural colors"
        - "monochrome"
        - "soft gradients"
      fantasy:
        - "vivid"
        - "muted earth tones"
        - "dark fantasy"
    
    resolution: "1024x1024"  # Square format for posts, supported by DALL-E 3
    
  stories:
    enabled: true
    count: 5
    genres: 
      - abstract
      - game
      - movie
      - portrait
      - photography
      - fantasy
    styles: &styles
      abstract:
        - "surreal"
        - "modern"
        - "cubist"
        - "minimalist"
      game:
        - "pixel art"
        - "hand-painted"
        - "3D render"
      movie:
        - "cinematic"
        - "dramatic"
        - "realistic"
      portrait:
        - "realistic"
        - "digital painting"
        - "classical"
      photography:
        - "cinematic"
        - "photorealistic"
        - "documentary"
      fantasy:
        - "dark surrealism"
        - "fantasy painting"
        - "mythical"
    themes: &themes
      abstract:
        - "geometric chaos"
        - "color burst"
        - "dreamscapes"
      game:
        - "cyberpunk city"
        - "alien planet"
        - "fantasy world"
      movie:
        - "sci-fi epic"
        - "cosmic horror"
        - "historical drama"
      portrait:
        - "fantasy character"
        - "mystical figure"
        - "regal elegance"
      photography:
        - "urban exploration"
        - "minimalist design"
        - "nature's beauty"
      fantasy:
        - "mystical realms"
        - "ancient gods"
        - "post-apocalyptic worlds"
    palettes: &palettes
      abstract:
        - "vivid"
        - "monochrome"
        - "gradient"
      game:
        - "vivid"
        - "dark"
        - "neon"
      movie:
        - "monochrome"
        - "cool tones"
        - "warm tones"
      portrait:
        - "soft pastels"
        - "monochrome"
        - "vivid"
      photography:
        - "natural colors"
        - "monochrome"
        - "soft gradients"
      fantasy:
        - "vivid"
        - "muted earth tones"
        - "dark fantasy"
    resolution: "1024x1024"  # Story format, supported by DALL-E 3

scheduling:
  daily_runs:
    - time: "12:00"  # Sabah erken
      enabled: true
    - time: "15:00"  # Öğlen
      enabled: true
    - time: "20:30"  # Akşam
      enabled: true

captions:
  # Caption generation settings
  use_emojis: true
  hashtag_style: "comprehensive"  # Options: minimal, comprehensive, none
  custom_hashtags: 
    - "#AIArt"
    - "#GenerativeArt"
    - "#CreativeTechnology"

logging:
  # Logging configuration
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "ai_post_pipeline.log"
  console_output: true

error_handling:
  # Error management settings
  retry_attempts: 3
  retry_delay_minutes: 15
  send_error_notifications: false
  notification_email: ""  # Add email for error notifications

social_media:
  # Platform-specific settings
  instagram:
    enabled: true
    post_types:  # What can be posted
      - feed_post
      - story
    max_daily_posts: 5
  
  # Future expansion for other platforms
  # twitter:
  #   enabled: false
  # facebook:
  #   enabled: false

ai_generation:
  # AI image generation settings
  provider: "openai"  # Could support multiple providers in future
  image_quality: "standard"  # Options: standard, high, low
  creativity_level: 0.7  # 0-1 range for prompt creativity

# Experimental features (future expansions)
experimental:
  multi_language_captions: false
  genre_rotation_strategy: "random"  # Could implement more sophisticated rotation